# remove default prefix
unbind C-b 

# set new prefix 
set-option -g prefix C-Space
bind-key C-Space send-prefix

# windows
bind t new-window
bind c kill-window

# splits 
bind v split-window -h
bind h split-window -v

bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-k select-pane -U
bind -n C-j select-pane -D

bind x kill-pane

# popup
bind f popup -w 80% -h 80%

# misc 
bind r source ~/.config/tmux/tmux.conf
